name: Cal.com Cron

on:
  schedule:
    - cron: "*/5 * * * *"    # every 5 minutes (UTC)
    - cron: "*/15 * * * *"   # every 15 minutes (UTC)
    - cron: "0 * * * *"      # hourly (UTC)
  workflow_dispatch: {}       # allow manual run for testing

jobs:
  every_5_min:
    if: github.event.schedule == '*/5 * * * *' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      APP_URL: ${{ secrets.APP_URL }}
      CRON_API_KEY: ${{ secrets.CRON_API_KEY }}
    steps:
      - name: webhookTriggers (*/5)
        run: |
          curl -sS --retry 3 --retry-delay 2 --fail-with-body \
            -X POST "$APP_URL/api/cron/webhookTriggers" \
            -H "authorization: $CRON_API_KEY"

  every_15_min:
    if: github.event.schedule == '*/15 * * * *' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      APP_URL: ${{ secrets.APP_URL }}
      CRON_API_KEY: ${{ secrets.CRON_API_KEY }}
    strategy:
      matrix:
        endpoint:
          - "/api/cron/bookingReminder"
          # Uncomment the ones you actually use:
          # - "/api/cron/workflows/scheduleEmailReminders"
          # - "/api/cron/workflows/scheduleSMSReminders"
          # - "/api/cron/workflows/scheduleWhatsappReminders"
    steps:
      - name: Hit ${{ matrix.endpoint }} (*/15)
        run: |
          curl -sS --retry 3 --retry-delay 2 --fail-with-body \
            -X POST "$APP_URL${{ matrix.endpoint }}" \
            -H "authorization: $CRON_API_KEY"

  hourly:
    if: github.event.schedule == '0 * * * *' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      APP_URL: ${{ secrets.APP_URL }}
      CRON_API_KEY: ${{ secrets.CRON_API_KEY }}
    steps:
      - name: changeTimeZone (hourly)
        run: |
          curl -sS --retry 3 --retry-delay 2 --fail-with-body \
            -X POST "$APP_URL/api/cron/changeTimeZone" \
            -H "authorization: $CRON_API_KEY"
      # Keep only if you use SMS pricing sync; otherwise remove:
      - name: checkSmsPrices (hourly, optional)
        run: |
          curl -sS --retry 3 --retry-delay 2 --fail-with-body \
            -X POST "$APP_URL/api/cron/checkSmsPrices" \
            -H "authorization: $CRON_API_KEY" || true
